crud_prj/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'crud_prj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^people/', include('people_app.urls')),
]

people_app/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from people_app.views import PeopleList, ViewPerson, NewPerson, KillPerson,\
    EditPerson, ViewCategory, EditCategory, DeleteCategory, CategoryDetail,\
    NewCategory, CategoryList

person_urls = patterns('',
    url(r'^$', ViewPerson.as_view(), name='person_detail'),
    url(r'^Update$', EditPerson.as_view(), name='person_update'),
    url(r'^Delete$', KillPerson.as_view(), name='person_delete'),
)

category_urls = patterns('',
    url(r'^$', ViewCategory.as_view(), name='category_detail'),
    url(r'^Alternate$', CategoryDetail.as_view(), name='category_detail_alt'),
    url(r'^Update$', EditCategory.as_view(), name='category_update'),
    url(r'^Delete$', DeleteCategory.as_view(), name='category_delete'),
)

urlpatterns = patterns('',
    url(r'^$', PeopleList.as_view(), name='people_list'),
    url(r'^(?P<slug>[\w-]+).person/', include(person_urls)),
    url(r'^NewPerson$', NewPerson.as_view(), name='person_add'),
    url(r'^Categories$', CategoryList.as_view(), name='category_list'),
    url(r'^(?P<slug>[\w-]+).cat/', include(category_urls)),
    url(r'^NewCategory$', NewCategory.as_view(), name='category_add'),
)

people_app/models.py
from django.db import models
from django.template.defaultfilters import slugify
from phonenumber_field.modelfields import PhoneNumberField


class Category(models.Model):
    title = models.CharField(max_length=80)
    slug = models.SlugField(blank=True)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):  # __unicode__ on Python 2
        return u"%s" % self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Category, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('category_detail', [self.slug])

    @models.permalink
    def get_update_url(self):
        return ('category_update', [self.slug])

    @models.permalink
    def get_delete_url(self):
        return ('category_delete', [self.slug])


class Person(models.Model):
    PROXIMITY_LIST = (
        (0, 'Not sure'),
        ('Friends', (
            (10, 'Best friends forever'),
            (20, 'Close friends'),
            (30, 'Distant friends'),
            (40, 'Enemies til the end')
        )),
        ('Family', (
            (50, 'Super close'),
            (60, 'Only on occasion'),
            (70, 'Only at funerals'),
            (80, 'Family grouch!')
        )),
    )
    first_name = models.CharField(max_length=60, help_text='Their first name')
    last_name = models.CharField(max_length=80, blank=True, help_text='Do you know it?')
    slug = models.SlugField(blank=True)
    category = models.ForeignKey(Category, blank=True, null=True, help_text='File this person where?')
    proximity = models.PositiveSmallIntegerField(choices=PROXIMITY_LIST, help_text='How much of a distance to keep?')
    home_phone = PhoneNumberField(blank=True)
    cell_phone = PhoneNumberField(blank=True)
    email = models.EmailField(blank=True, help_text='Do they have an Email address?')
    added_on = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'people'
        ordering = ['last_name']

    @property
    def full_name(self):
        return u"%s %s" % (self.first_name, self.last_name) if self.last_name != '' else u"%s" % self.first_name

    def __str__(self):  # __unicode__ on Python 2
        return u"%s, %s" % (self.last_name, self.first_name) if self.last_name != '' else u"%s" % self.first_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.full_name)
        return super(Person, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('person_detail', [self.slug])

    @models.permalink
    def get_update_url(self):
        return ('person_update', [self.slug])

    @models.permalink
    def get_delete_url(self):
        return ('person_delete', [self.slug])

people_app/forms.py
from django import forms
from people_app.models import Category, Person


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('title',)


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'category', 'proximity', 'home_phone', 'cell_phone', 'email',)

people_app/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from people_app.models import Category, Person
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from people_app.forms import CategoryForm, PersonForm
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse


class CategoryMixin(object):
    model = Category

    '''
    def get_context_data(self, **kwargs):
        kwargs.update({'object_name': 'Category'})
        return kwargs
    '''


class CategoryFormMixin(CategoryMixin):
    form_class = CategoryForm
    template_name = 'people_app/object_form.html'


class CategoryList(CategoryMixin, ListView):
    template_name = 'people_app/object_category_list.html'


class CategoryDetail(CategoryMixin, DetailView):
    pass


class NewCategory(CategoryFormMixin, CreateView):
    pass


class EditCategory(CategoryFormMixin, UpdateView):
    pass


class DeleteCategory(CategoryMixin, DeleteView):
    template_name = 'people_app/object_confirm_delete.html'

    def get_success_url(self):
        return reverse('category_list')


class PersonMixin(object):
    model = Person

    '''
    def get_context_data(self, **kwargs):
        kwargs.update({'object_name': 'Person'})
        return kwargs
    '''


class PersonFormMixin(PersonMixin):
    form_class = PersonForm
    template_name = 'people_app/object_form.html'


class PeopleList(PersonMixin, ListView):
    template_name = 'people_app/object_list.html'


class ViewPerson(PersonMixin, DetailView):
    pass


class NewPerson(PersonFormMixin, CreateView):
    pass


class EditPerson(PersonFormMixin, UpdateView):
    pass


class KillPerson(PersonMixin, DeleteView):
    template_name = 'people_app/object_confirm_delete.html'

    def get_success_url(self):
        return reverse('people_list')


class ViewCategory(PersonMixin, ListView):
    template_name = 'people_app/object_list.html'

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return super(ViewCategory, self).get_queryset().filter(category=self.category)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <title>{% block title %}Untitled{% endblock %} | Phone Directory</title>
   <!-- Le styles -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/vigilancia_prj.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to vigilancia_prj.css -->
    {% block extra_css %}{% endblock extra_css %}
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Personas</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'people_list' %}">Index</a></li>
            <li class="active"><a href="{% url 'category_list' %}">Categories</a></li>
            
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {% if user.username %}
                      {{ user.get_full_name|default:"User" }}
                    {% else %}
                       Sesión de usuarios
                    {% endif %}  
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                   {% if user.username %}
                      
                      <li>
                        <a href="#"><i class="icon-off"></i> Mi perfil de usuario</a>
                      </li>  
                      </li>
                      <li class="divider"></li>
                      <li>
                        <a tabindex="-1" href="/accounts/logout"><i class="icon-off"></i> Cerrar sesión</a>
                      </li>  
                      
                    {% else %}
                       <li>
                        <a tabindex="-1" href="/accounts/login/"><i class="icon-eye-open"></i> Iniciar sesión</a>
                        </li>
                    {% endif %}
                </ul>
              </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
        {% block content %}
        The end user should never ever see this!
        {% endblock %}
    </div>


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/vigilancia_prj.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}


</body>
</html>

templates/people_app/object_category_list.html
{% extends 'base.html' %}

{% block title %}{{object_name}} List{% endblock %}

{% block content %}
 

    <table class="table table-striped">
    <thead><tr><th>Name</th><th>Action</th></tr></thead>
    <tbody>
      {% for object in object_list %}
      <tr><td><a href="{{object.get_absolute_url}}">{{object}}</a></td><td><a href="{{object.get_update_url}}">Update</a> | <a href="{{object.get_delete_url}}">Delete</a></td></tr>
      {% endfor %}
    </tbody>
    </table>

    <br><br>
    <a href="{% url 'category_add' %}" class="btn btn-primary">Add category</a>

{% endblock %}

templates/people_app/object_confirm_delete.html
{% extends 'base.html' %}

{% block title %}{{object_name}} Confirm delete?{% endblock %}

{% block content %}
<h3>Are you sure you want to delete {{object}}?</h3>
<form action="" method="post">{% csrf_token %}
<input type="submit" value="Yes!"/>  <input type="button" value="No..." onclick="window.history.go(-1);"/>
</form>
{% endblock %}

templates/people_app/object_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block title %}{{object_name}} Form{% endblock %}

{% block content %}
<h3>{% if object %}Updating {{object}}{% else %}Add a new {{object_name}}{% endif %}</h3>
<form action="" method="post">{% csrf_token %}
<table>
{{form|bootstrap}}
</table>
<input type="submit" value="Save {{object_name}}"/></form>
{% endblock %}

templates/people_app/object_list.html
{% extends 'base.html' %}

{% block title %}{{object_name}} List{% endblock %}

{% block content %}
 

    <table class="table table-striped">
    <thead><tr><th>Name</th><th>Action</th></tr></thead>
    <tbody>
      {% for object in object_list %}
      <tr><td><a href="{{object.get_absolute_url}}">{{object}}</a></td><td><a href="{{object.get_update_url}}">Update</a> | <a href="{{object.get_delete_url}}">Delete</a></td></tr>
      {% endfor %}
    </tbody>
    </table>

    <br><br>
    <a href="{% url 'person_add' %}" class="btn btn-primary">Add person</a>

{% endblock %}

templates/people_app/person_detail.html
{% extends 'base.html' %}

{% block title %}{{object}}{% endblock %}

{% block content %}
<table>
<tr><th>Full name:</th><td>{{object.full_name}}</td></tr>
<tr><th>Filed under:</th><td><a href="{{object.category.get_absolute_url}}">{{object.category}}</a></td></tr>
<tr><th>Proximity:</th><td>{{object.get_proximity_display}}</td></tr>
{% if object.home_phone %}<tr><th>Home Phone:</th><td>{{object.home_phone}}</td></tr>{% endif %}
{% if object.cell_phone %}<tr><th>Cell Phone:</th><td>{{object.cell_phone}}</td></tr>{% endif %}
{% if object.email %}<tr><th>Email:</th><td>{{object.email}}</td></tr>{% endif %}
</table>
<a href="{{object.get_update_url}}">Update</a> | <a href="{{object.get_delete_url}}">Delete</a>
{% endblock %}